apiVersion: v2
name: upf-loadtest-webui
description: Web control plane for Travelping UPF PFCP and TRex load tests
type: application
version: 0.1.26
appVersion: "0.1.26"
home: https://github.com/infinitydon/upf-loadtest-webui
maintainers:
  - name: infinitydon
    url: https://github.com/infinitydon
