{{- if and (not .Values.auth.existingSecret) .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upf-loadtest-webui.fullname" . }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
